# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dacf136c3c814a8ea0e02fd91b4dcc3b5183d0261731cd630df70b33eae9c4ea296ba2157fe795053aaa892b3e1883a43b05cbe605b272f823be02b699cd7a5d

test:
  secret_key_base: a5be2e13d14991b4ff51bb4155a202a7c4dcc06aa2580b7fc34d9eea7b9d2fd02c014298637cfcc249bd4646575d0b271db7adfa8122e7bc7a5a8ac5e5bc1cd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
